name: DoorCloser
version: "1.1"
description: Close doors behind players
author: Kirastur
website: https://github.com/Kirastur/DoorCloserNukkit/wiki

api: ["1.0.13"]
load: POSTWORLD
main: de.polarwolf.doorcloser.main.Main

permissions:
    doorcloser.admin:
        description: Should user be able to command the doorclosing-butler?
        default: op
